name: Java CI
on: push
jobs:
  Clone-down:
    needs:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ci/build-app.sh
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Unit Test
        run: ci/unit-test-app.sh
        
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
         name: code
         path: .